name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Install Linux dependencies for Fyne
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libx11-dev libxrandr-dev libxinerama-dev \
          libxcursor-dev libxi-dev libxxf86vm-dev \
          mesa-common-dev libgl1-mesa-dev

    - name: Install MinGW for Windows build
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64

    - name: Create build directories
      run: |
        mkdir -p build/linux
        mkdir -p build/windows

    - name: Build (Linux)
      run: |
        export CGO_ENABLED=1
        go mod tidy
        go build -v -o build/linux/env-invoices ./main.go

    - name: Build Windows binary (no console)
      run: |
        export GOOS=windows
        export GOARCH=amd64
        export CC=x86_64-w64-mingw32-gcc
        export CXX=x86_64-w64-mingw32-g++
        export CGO_ENABLED=1
        go mod tidy
        go build -v -ldflags="-H=windowsgui" -o build/windows/env-invoices.exe ./main.go

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: env-invoices-linux
        path: build/linux/env-invoices

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: env-invoices-windows
        path: build/windows/env-invoices.exe
