name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Linux dependencies for Fyne
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libx11-dev libxrandr-dev libxinerama-dev \
          libxcursor-dev libxi-dev libxxf86vm-dev \
          mesa-common-dev libgl1-mesa-dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build (Linux)
      run: go build -v -o build/linux/env-invoices ./main.go

    - name: Build (Windows)
      run: GOOS=windows GOARCH=amd64 go build -v -o build/windows/env-invoices.exe ./main.go

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: env-invoices-linux
        path: build/linux/env-invoices

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: env-invoices-windows
        path: build/windows/env-invoices.exe
