name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build (Linux)
      run: go build -v -o build/linux/env-invoices ./...

    - name: Build (Windows)
      run: GOOS=windows GOARCH=amd64 go build -v -o build/windows/env-invoices.exe ./...
